In [70]:
import geopandas
import pandas as pd
from sqlalchemy import create_engine, inspect

In [64]:
def get_sql_query(tabla: str, esquema: str = 'public') -> str:
    sql = f"SELECT * FROM {esquema}.{tabla}"
    return sql

In [71]:
engine = create_engine('postgresql://postgres:ficticio@200.48.19.4:9006/forestal_pre')

# BASE DE DATOS

In [72]:
# ANÁLISIS DE LA TABLA
# ==================== PARÁMETROS ====================
ESQUEMA = 'modalidad_acceso'
TABLA = 'autcuafa'
# ==================== PARÁMETROS ====================

inspector = inspect(engine)
columns = inspector.get_columns(TABLA, schema=ESQUEMA)
df_table = pd.DataFrame(columns)
df_table

,name,type,nullable,default,autoincrement,comment
0,gid,INTEGER,False,nextval('modalidad_acceso.autcuafa_id_seq'::re...,True,None
1,coddoc,VARCHAR(190),True,None,False,None
2,numaut,VARCHAR(50),True,None,False,None
3,nomtit,VARCHAR(255),True,None,False,None
4,nomrel,VARCHAR(255),True,None,False,None
5,numruc,VARCHAR(11),True,None,False,None
6,tipdoc,SMALLINT,True,None,False,None
7,nrodoc,VARCHAR(10),True,None,False,None
8,doctit,VARCHAR(100),True,None,False,None
9,codcat,VARCHAR(15),True,None,False,None
10,sector,VARCHAR(100),True,None,False,None
11,supsig,"NUMERIC(10, 4)",True,None,False,None
12,supsol,"NUMERIC(10, 4)",True,None,False,None
13,subtot,"NUMERIC(10, 4)",True,None,False,None
14,subtit,"NUMERIC(10, 4)",True,None,False,None
15,nomdep,VARCHAR(2),True,None,False,None
16,nompro,VARCHAR(150),True,None,False,None
17,nomdis,VARCHAR(150),True,None,False,None
18,autfor,SMALLINT,True,None,False,None
19,docleg,VARCHAR(100),True,None,False,None
20,fecleg,DATE,True,None,False,None
21,fecini,DATE,True,None,False,None
22,fecter,DATE,True,None,False,None
23,pago,"NUMERIC(9, 3)",True,None,False,None
24,volapr,"NUMERIC(9, 3)",True,None,False,None
25,supres,"NUMERIC(10, 4)",True,None,False,None
26,destin,SMALLINT,True,None,False,None
27,geom,"geometry(MULTIPOLYGON,32719)",True,None,False,None
28,proreg,VARCHAR(190),True,None,False,None
29,fecreg,DATE,True,('now'::text)::date,False,None
30,resreg,VARCHAR(190),True,None,False,None
31,fuente,VARCHAR(100),True,None,False,None
32,fecmod,TIMESTAMP,True,None,False,None
33,resmod,VARCHAR(190),True,None,False,None
34,resmod_s,VARCHAR(190),True,None,False,None
35,tipaut,"NUMERIC(5, 0)",True,None,False,None
36,docreg,VARCHAR(100),True,None,False,None
37,observ,VARCHAR(255),True,None,False,None
38,zonutm,"NUMERIC(2, 0)",True,None,False,None
39,origen,"NUMERIC(1, 0)",True,None,False,None
40,estreg,"NUMERIC(1, 0)",True,None,False,None
41,idper,"NUMERIC(1, 0)",True,None,False,None

## ANÁLISIS DEL OBJETO

In [74]:
# CREACIÓN DEL DATA FRAME
# ==================== PARÁMETROS ====================
ESQUEMA = 'modalidad_acceso'
TABLA = 'autcuafa'
# ==================== PARÁMETROS ====================

df_object = geopandas.read_postgis(get_sql_query(TABLA, ESQUEMA), engine)

### INFORMACIÓN BÁSICA DEL OBJETO

![Tipos](https://pbpython.com/images/pandas_dtypes.png)

In [75]:
df_object.head(10)

,gid,coddoc,numaut,nomtit,nomrel,numruc,tipdoc,nrodoc,doctit,codcat,...,fecmod,resmod,resmod_s,tipaut,docreg,observ,zonutm,origen,estreg,idper
0,22,None,17-MAD-TAM/AUT-CUP-2021-22,ELSA PACCO HUARCA,ELSA PACCO HUARCA,10461696142,1,46169614,TITULO DE PROPIEDAD RURAL,060576,...,None,None,None,80102.0,None,FECHA DE TERMINO DE VIGENCIA NO ESPECIFICA,19.0,5.0,4.0,6.0
1,23,None,17-MAD-TAH-AUT-CUP-2021-01,MARIA MAGDALENA CURO ARQQUE,MARIA MAGDALENA CURO ARQQUE,10476972251,1,47697225,PARTIDA REGISTRAL,None,...,None,None,None,80102.0,None,"FECHA DE TERMINO DE VIGENCIA NO ESPECIFICA, NO...",19.0,5.0,4.0,6.0
2,1,None,17-MAD-TAM/AUT-CUP-2021-01,GUMERCINDO APAZA HUARCA,GUMERCINDO APAZA HUARCA,10450621078,1,45062107,TITULO DE PROPIEDAD,067193,...,None,None,None,80102.0,None,None,19.0,5.0,4.0,6.0
3,24,None,17-MAD-TAH-AUT-CUP-2021-02,DOLIBETH REYNA DE MORENO,DOLIBETH REYNA DE MORENO,10050609095,1,05060909,CERTIFICADO CATASTRAL,042125,...,None,None,None,80102.0,None,NO SE ENCONTRO INFORMACION DE PAGO POR APROVEC...,19.0,5.0,4.0,6.0
4,20,None,17-MAD-TAM/AUT-CUP-2021-20,NOE ARRIOLA VALENCIA,NOE ARRIOLA VALENCIA,10423010156,1,42301015,PARTIDA REGISTRAL,None,...,None,None,None,80102.0,None,NO SE TIENE CODIGO CATASTRAL,19.0,5.0,4.0,6.0
5,25,None,17-MAD-TAM/AUT-CUP-2020-06,SARA TORRES QUISPE,SARA TORRES QUISPE,10722830402,1,72283040,TITULO DE PROPIEDAD RURAL,067152,...,None,None,None,80102.0,None,"FECHA DE TERMINO DE VIGENCIA NO ESPECIFICA, NO...",19.0,5.0,4.0,6.0
6,3,None,17-MAD-TAM/AUT-CUP-2021-03,FELIX CHUQUIRI MACHACA,FELIX CHUQUIRI MACHACA,10800737694,1,80073769,TITULO DE PROPIEDAD,031090,...,None,None,None,80102.0,None,None,19.0,5.0,4.0,6.0
7,4,None,17-MAD-TAM/AUT-CUP-2021-04,MARIELA LOURDES OLIVARES NAVARRO,MARIELA LOURDES OLIVARES NAVARRO,10774927064,1,77492706,TITULO DE PROPIEDAD,060646,...,None,None,None,80102.0,None,None,19.0,5.0,4.0,6.0
8,2,None,17-MAD-TAM/AUT-CUP-2021-02,ELOY ORESTES CHAMBI CHURA,ELOY ORESTES CHAMBI CHURA,10404982031,1,40498203,REGISTRO DE PREDIOS,031125,...,None,None,None,80102.0,None,None,19.0,5.0,4.0,6.0
9,6,None,17-MAD-TAM/AUT-CUP-2021-06,ALBINO BAUTISTA GASTELU,ALBINO BAUTISTA GASTELU,10048093111,1,04809311,TITULO DE PROPIEDAD,30350,...,None,None,None,80102.0,None,None,19.0,5.0,4.0,6.0

In [76]:
# Información del data frame
df_object.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 42 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   gid       25 non-null     int64
 1   coddoc    0 non-null      object
 2   numaut    25 non-null     object
 3   nomtit    25 non-null     object
 4   nomrel    25 non-null     object
 5   numruc    25 non-null     object
 6   tipdoc    25 non-null     int64
 7   nrodoc    25 non-null     object
 8   doctit    25 non-null     object
 9   codcat    23 non-null     object
 10  sector    25 non-null     object
 11  supsig    25 non-null     float64
 12  supsol    25 non-null     float64
 13  subtot    25 non-null     float64
 14  subtit    25 non-null     float64
 15  nomdep    25 non-null     object
 16  nompro    25 non-null     object
 17  nomdis    25 non-null     object
 18  autfor    25 non-null     int64
 19  docleg    25 non-null     object
 20  fecleg    25 non-null     object
 21  fecini    25 non-null     object
 22  fecter    24 non-null     object
 23  pago      24 non-null     float64
 24  volapr    25 non-null     float64
 25  supres    23 non-null     float64
 26  destin    25 non-null     int64
 27  geom      25 non-null     geometry
 28  proreg    0 non-null      object
 29  fecreg    25 non-null     object
 30  resreg    0 non-null      object
 31  fuente    25 non-null     object
 32  fecmod    0 non-null      object
 33  resmod    0 non-null      object
 34  resmod_s  0 non-null      object
 35  tipaut    25 non-null     float64
 36  docreg    0 non-null      object
 37  observ    12 non-null     object
 38  zonutm    25 non-null     float64
 39  origen    25 non-null     float64
 40  estreg    25 non-null     float64
 41  idper     25 non-null     float64
dtypes: float64(12), geometry(1), int64(4), object(25)
memory usage: 8.3+ KB

In [77]:
df_object.isnull().sum()

gid          0
coddoc      25
numaut       0
nomtit       0
nomrel       0
numruc       0
tipdoc       0
nrodoc       0
doctit       0
codcat       2
sector       0
supsig       0
supsol       0
subtot       0
subtit       0
nomdep       0
nompro       0
nomdis       0
autfor       0
docleg       0
fecleg       0
fecini       0
fecter       1
pago         1
volapr       0
supres       2
destin       0
geom         0
proreg      25
fecreg       0
resreg      25
fuente       0
fecmod      25
resmod      25
resmod_s    25
tipaut       0
docreg      25
observ      13
zonutm       0
origen       0
estreg       0
idper        0
dtype: int64